# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d00aecf50f78bd9493dfa95f5adefd338424299a1dfb3b01f2ad358952b9595a82dcb4f2a57f8cfaa4a50beb51f6acdbc5d926ecd51ac73cfe6b8f2fc80daada

test:
  secret_key_base: eb4ad894950f80d730687662288829bd282f5a209e56bc7d8c8c034d3f5d7c1c4b7c85775a31eecbf5bbbe2efbc910cf6263f51a552ba4ea002d2a66e2547f9c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
